version: "3.9"

services:
  ocr:
    build: ./ocr-api
    container_name: ocr-service
    ports:
      - "9880:9880"
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: 8g
